### ISSUE TITLE
cuDNN required in v6?

### ISSUE THREAD

**Issue by tgpfeiffer** [chainer/chainer#6134]
Chainer code that used to work fine with 5.2 does not work any more with 6.0.0b2, presumably because I don't have cuDNN installed.

* Conditions
  - Chainer version: 6.0.0b2
  - CuPy version: 6.0.0b2
  - OS/Platform: Ubuntu 16.04
  - CUDA/cuDNN version: CUDA 8.0/no cuDNN
* Code to reproduce: `python3 -c "from chainer.backends import cuda; cuda.check_cuda_available()"`
* Error messages, stack traces, or logs:
  ```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.5/dist-packages/chainer/backends/cuda.py", line 135, in 
  check_cuda_available
      raise RuntimeError(msg)
  RuntimeError: CUDA environment is not correctly set up
  (see https://github.com/chainer/chainer#installation).module 'cupy.cuda' has no attribute 'cudnn'
  ```

@hvy pointed out that this change https://github.com/chainer/chainer/commit/91878a45fe40fb2ea70ff9bbf3e9a9ef4ee6df56#diff-b74802247d24e96cf7d5d8742480530dR69 may be the cause.
