### PR TITLE
Modify detect training length

### PR DESCRIPTION
**Pull request by himkt**
Related to #3351 
I have tried to change the way to detect `training_length`.

### CODE REVIEW

**Comment by himkt** [comment]
I have changed the way to detect `training_length` in InternalTrigger and EarlyStoppingTrigger.
BTW, I found that there are errors in testing `test_manual_schedule_trigger.py` and `test_interval_trigger.py`, which occurs `master` branch.

**Comment by himkt** [comment]
I removed the WIP prefix because all checks were passed.
But in my developing environment, errors occurred in testing test_manual_schedule_trigger.py and test_interval_trigger.py, which also occurs master branch like below.
`AttributeError: module 'chainer.testing' has no attribute 'condition'`

What do I mistake or forget something which I have to do?

**Comment by himkt** [comment]
The test failures will be fixed in #4103 .

**Comment by himkt** [comment]
After #4103 was merged, I confirmed that tests for trigger and extension were passed.

File: chainer/training/extensions/progress_bar.py [hunk 1]
```diff
@@ -44,10 +43,10 @@ def __call__(self, trainer):
         # initialize some attributes at the first call
         if training_length is None:
             t = trainer.stop_trigger
-            if not isinstance(t, triggers.IntervalTrigger):
+            if not hasattr(t, '_get_training_length'):
```
Comment (beam2d) [inline chainer/training/extensions/progress_bar.py]: This method is used as an interface of trigger, so I think it's better not to prefix it by `_`. How about using `get_training_length`?

File: chainer/training/triggers/early_stopping_trigger.py [hunk 2]
```diff
@@ -45,6 +45,7 @@ def __init__(self, check_trigger=(1, 'epoch'), monitor='main/loss',
         self.monitor = monitor
         self.verbose = verbose
         self.already_warning = False
+        self.max_trigger = max_trigger  # TODO(This is confusing)
```
Comment (beam2d) [inline chainer/training/triggers/early_stopping_trigger.py]: How about making `max_trigger` argument accepting any trigger that supports `get_training_length`? Then, we do not need to add `self.max_trigger` and then can make `get_training_length` just delegates to `self._max_trigger.get_training_length()`.

File: chainer/training/extensions/progress_bar.py (hunk 1 above)
Comment (beam2d) [reply chainer/training/extensions/progress_bar.py]: I also feel it's more natural to let duck-typing check the code here. I mean just removing this if-then-raise block. What do you think? It will show the trigger type and the cause of the error (`'FooTrigger' object has no attribute 'get_training_length'`), which are more informative for users.

Comment (himkt) [reply chainer/training/extensions/progress_bar.py]: > This method is used as an interface of trigger
I understand! I remove the prefix.

Comment (himkt) [reply chainer/training/extensions/progress_bar.py]: > I also feel it's more natural to let duck-typing check the code here.

Thanks for the comment! I agree with your suggestion.
It would be better to show informations

File: chainer/training/triggers/early_stopping_trigger.py (hunk 2 above)
Comment (himkt) [reply chainer/training/triggers/early_stopping_trigger.py]: Thanks for the great suggestion! I remove `self.max_trigger` and use `self._max_trigger.get_training_length`.

**Comment by himkt** [comment]
Thanks for your kindly comments.
I update some implementation based on your suggestion.

**Comment by beam2d** [comment]
Jenkins, test this please

**Comment by beam2d** [comment]
LGTM

**Comment by beam2d** [comment]
Thank you!
