### PR TITLE
CuPy cannot be enabled when cuDNN is unavailable

### LINKED ISSUE #6134: cuDNN required in v6?
Chainer code that used to work fine with 5.2 does not work any more with 6.0.0b2, presumably because I don't have cuDNN installed.

* Conditions
  - Chainer version: 6.0.0b2
  - CuPy version: 6.0.0b2
  - OS/Platform: Ubuntu 16.04
  - CUDA/cuDNN version: CUDA 8.0/no cuDNN
* Code to reproduce: `python3 -c "from chainer.backends import cuda; cuda.check_cuda_available()"`
* Error messages, stack traces, or logs:
  ```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.5/dist-packages/chainer/backends/cuda.py", line 135, in 
  check_cuda_available
      raise RuntimeError(msg)
  RuntimeError: CUDA environment is not correctly set up
  (see https://github.com/chainer/chainer#installation).module 'cupy.cuda' has no attribute 'cudnn'
  ```

@hvy pointed out that this change https://github.com/chainer/chainer/commit/91878a45fe40fb2ea70ff9bbf3e9a9ef4ee6df56#diff-b74802247d24e96cf7d5d8742480530dR69 may be the cause.

### PR DESCRIPTION
**Pull request by kmaehashi**
Fixes #6134.

### CODE REVIEW

File: chainer/backends/cuda.py [hunk 1]
```diff
@@ -108,11 +107,17 @@ class Event(object):  # type: ignore # for type testing
...
-    # for `xp is cuda.cupy` and `cuda.libcudnn` to always work
+    # for `xp is chainer.backends.cuda.cupy` to always work
     cupy = object()
-    libcudnn = object()
+
 
 if available:
+    try:
+        libcudnn = cupy.cuda.cudnn  # type: tp.Any # NOQA
+    except Exception as e:
```
Comment (niboshi) [inline chainer/backends/cuda.py]: flake8 complains `e` is never used.

File: chainer/backends/cuda.py [hunk 2]
```diff
@@ -108,11 +107,17 @@ class Event(object):  # type: ignore # for type testing
...
 
-    # for `xp is cuda.cupy` and `cuda.libcudnn` to always work
+    # for `xp is chainer.backends.cuda.cupy` to always work
     cupy = object()
-    libcudnn = object()
+
 
 if available:
+    try:
+        libcudnn = cupy.cuda.cudnn  # type: tp.Any # NOQA
```
Comment (niboshi) [inline chainer/backends/cuda.py]: How about doing this only if `cudnn_enabled is True`?
(In that case I think this assignment should succeed?)

Comment (niboshi) [reply chainer/backends/cuda.py]: Ok, it could raise an error even if `cudnn = cupy.cudnn` succeeds
(because `cupy.cuda.cudnn` link to external libraries).

**Comment by niboshi** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
LGTM
