### ISSUE TITLE
Variable.backward causes an error when composing F.tile, F.sigmoid_cross_entropy, and F.sum.

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#4877]
An error occurs when we compose `F.tile`, `F.sigmoid_cross_entropy` (with `reduce=no`), and `F.sum` and do `Variable.backward` to the output variable.

* Target version: 3.2.0<= v <=master

Code to reproduce
```python
import chainer
from chainer import functions as F
import numpy as np

chainer.print_runtime_info()

y = chainer.Variable(np.random.standard_normal((12, 10)).astype(np.float32))
t = chainer.Variable(np.random.standard_normal((12, 1)).astype(np.int32))
size = 10

t = F.tile(t, (1, size))
loss = F.sigmoid_cross_entropy(y, t, reduce="no")
loss = F.sum(loss)
loss.backward()
```

Log
```
Chainer: 5.0.0b1
NumPy: 1.11.3
CuPy: Not Available
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    loss.backward()
  File "/home/delta/dev/chainer/chainer/variable.py", line 966, in backward
    self._backward_main(retain_grad, loss_scale)
  File "/home/delta/dev/chainer/chainer/variable.py", line 1095, in _backward_main
    target_input_indexes, out_grad, in_grad)
  File "/home/delta/dev/chainer/chainer/function_node.py", line 548, in backward_accumulate
    gxs = self.backward(target_input_indexes, grad_outputs)
  File "/home/delta/dev/chainer/chainer/functions/array/tile.py", line 50, in backward
    for i in range(gy.ndim):
  File "/home/delta/dev/chainer/chainer/variable.py", line 703, in ndim
    return self.data.ndim
AttributeError: 'NoneType' object has no attribute 'ndim'
```

The error did not occur if we change in either way:
- Remove `F.tile`.
- Remove `F.sum` and change `reduce` option of `F.sigmoid_cross_entropy` to `mean`.

I did `git bisect` and found that the first bad commit was #3705. So, I suspect `F.sigmoid_cross_entropy`.

**Comment by toslunar** [comment]
It seems backward of `F.sigmoid_cross_entropy` returns `Variable(None)` for the gradient of `t`, which should be `None`.
```
y = chainer.Variable(np.random.standard_normal((12, 10)).astype(np.float32))
t = chainer.Variable(np.random.standard_normal((12, 10)).astype(np.int32))

loss = F.sigmoid_cross_entropy(y, t, reduce="no")
loss = F.sum(loss)
print(chainer.grad([loss], [t]))  # => Variable(None)
```

**Comment by toslunar** [comment]
It seems backward of `F.sigmoid_cross_entropy` returns `Variable(None)` for the gradient of `t`, which should be `None`.
```
y = chainer.Variable(np.random.standard_normal((12, 10)).astype(np.float32))
t = chainer.Variable(np.random.standard_normal((12, 10)).astype(np.int32))

loss = F.sigmoid_cross_entropy(y, t, reduce="no")
loss = F.sum(loss)
print(chainer.grad([loss], [t]))  # => [Variable(None)]
```
